inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/LineLength:
  Exclude:
    - 'app/helpers/requests/application_helper.rb'
    - 'spec/helpers/requests/application_helper_spec.rb'
    - 'app/helpers/requests/request_helper.rb'
    - 'app/models/concerns/requests/voyager.rb'
    - 'app/models/requests/borrow_direct_lookup.rb'
    - 'app/models/requests/submission.rb'
    - 'spec/controllers/requests/request_controller_spec.rb'
    - 'spec/models/requests/pickup_lookup_spec.rb'
    - 'spec/models/requests/recall_spec.rb'

RSpec/MultipleExpectations:
  Max: 5

Style/FrozenStringLiteralComment:
  Enabled: false
