inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/requests/requestable.rb'
    - 'app/controllers/requests/request_controller.rb'
    - 'app/helpers/requests/application_helper.rb'
    - 'app/models/concerns/requests/aeon.rb'
    - 'app/models/concerns/requests/ctx.rb'
    - 'app/models/concerns/requests/illiad.rb'
    - 'app/models/requests/recall.rb'
    - 'app/models/requests/request.rb'
    - 'app/models/requests/router.rb'
    - 'app/models/requests/submission.rb'

Metrics/LineLength:
  Exclude:
    - 'app/helpers/requests/application_helper.rb'
    - 'spec/helpers/requests/application_helper_spec.rb'
    - 'app/helpers/requests/request_helper.rb'
    - 'app/models/concerns/requests/voyager.rb'
    - 'app/models/requests/borrow_direct_lookup.rb'
    - 'app/models/requests/submission.rb'
    - 'spec/controllers/requests/request_controller_spec.rb'
    - 'spec/models/requests/pickup_lookup_spec.rb'
    - 'spec/models/requests/recall_spec.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/requests/requestable.rb'
    - 'app/controllers/requests/request_controller.rb'
    - 'app/helpers/requests/application_helper.rb'
    - 'app/models/concerns/requests/aeon.rb'
    - 'app/models/concerns/requests/ctx.rb'
    - 'app/models/concerns/requests/illiad.rb'
    - 'app/models/requests/recall.rb'
    - 'app/models/requests/request.rb'
    - 'app/models/requests/router.rb'
    - 'app/models/requests/submission.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/models/requests/recap_spec.rb'

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Exclude:
    - 'spec/models/requests/recap_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
