inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive
  Exclude:
    - 'spec/models/requests/recap_spec.rb'

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Exclude:
    - 'spec/models/requests/recap_spec.rb'
    - 'spec/models/requests/request_spec.rb'
    - 'spec/models/requests/router_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'spec/factories/requests/users.rb'
