sudo: required
language: ruby
rvm:
  - 2.3.1
  - 2.4.0
env:
  - RAILS_VERSION="4.2.8"
dist: trusty

addons:
  chrome: stable

before_install:
  - gem update --system
  - gem install bundler
  - apt-get install chromium-chromedriver
  - ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

script: bundle exec rake ci

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
