sudo: required
language: ruby
rvm:
  - 2.4.1
env:
  - RAILS_VERSION="5.1.2"
dist: trusty

addons:
  chrome: stable

before_install:
  - gem update --system
  - gem install bundler -v 1.17.3

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - bundle install
  - bundle exec rake ci

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
