language: ruby
rvm:
  - 2.2.0
  - 2.3.0

# before_script:
#   - rake engine_cart:generate

script: bundle exec rake ci

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - "tampakis@princeton.edu"
      - "jstroop@princeton.edu"
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"