language: ruby
rvm:
  - 2.3.0

before_script:
  - rake engine_cart:generate

script: bundle exec rspec

branches:
  only:
    - master
notifications:
  email:
    recipients:
      - "tampakis@princeton.edu"
      - "jstroop@princeton.edu"
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"