language: ruby
rvm:
  - 2.3.1
  - 2.4.0
env:
  - RAILS_VERSION="4.2.8"
dist: trusty

before_install:
  - gem update --system
  - gem install bundler

script: bundle exec rake ci

branches:
  only:
    - development
notifications:
  email:
    recipients:
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
